# Generated by Django 3.2 on 2023-08-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('-', 'Prefer Not To Say')], default='-', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photo'),
        ),
    ]
