# Generated by Django 3.2 on 2023-09-12 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='playlist_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
