# Generated by Django 3.2 on 2023-09-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_playlist_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='likes',
        ),
    ]
