# Generated by Django 3.2 on 2023-08-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.AlterField(
            model_name='album',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='total_streams',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='total_streams',
            field=models.IntegerField(default=0),
        ),
    ]
