# Generated by Django 3.2 on 2023-08-30 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20230829_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover_photo',
            field=models.ImageField(default='default_cover_photo.jpg', upload_to='album_cover_photo'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio_file'),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
