# Generated by Django 3.2 on 2023-08-30 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_auto_20230830_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='Album_Like',
            new_name='AlbumLike',
        ),
        migrations.RemoveField(
            model_name='album',
            name='total_likes',
        ),
        migrations.RemoveField(
            model_name='album',
            name='total_streams',
        ),
        migrations.DeleteModel(
            name='Song_Like',
        ),
    ]
