# Generated by Django 3.2 on 2023-09-04 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0006_auto_20230901_0653'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('artist', 'album_name')},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'song_name')},
        ),
    ]
