# Generated by Django 3.2 on 2023-09-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20230904_0719'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'track_number'), ('album', 'song_name')},
        ),
    ]
