# Generated by Django 3.2 on 2023-09-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20230912_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
