# Generated by Django 3.2 on 2023-09-13 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0009_auto_20230912_0737'),
        ('playlists', '0002_alter_playlist_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('liked_albums', models.ManyToManyField(blank=True, related_name='user_album_likes', to='songs.Album')),
                ('liked_playlists', models.ManyToManyField(blank=True, related_name='user_playlist_likes', to='playlists.Playlist')),
                ('liked_songs', models.ManyToManyField(blank=True, related_name='user_song_likes', to='songs.Song')),
                ('recently_played_albums', models.ManyToManyField(blank=True, related_name='recently_played_albums', to='songs.Album')),
                ('recently_played_playlists', models.ManyToManyField(blank=True, related_name='recently_played_playlists', to='playlists.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
