# Generated by Django 3.2 on 2023-09-14 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_remove_playlist_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0010_auto_20230914_0934'),
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecentlyPlayedPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='RecentlyPlayedAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.album')),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.userdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='recently_played_albums',
        ),
        migrations.AddField(
            model_name='userdata',
            name='recently_played_albums',
            field=models.ManyToManyField(blank=True, related_name='recently_played_albums', through='userdata.RecentlyPlayedAlbums', to='songs.Album'),
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='recently_played_playlists',
        ),
        migrations.AddField(
            model_name='userdata',
            name='recently_played_playlists',
            field=models.ManyToManyField(blank=True, related_name='recently_played_playlists', through='userdata.RecentlyPlayedPlaylists', to='playlists.Playlist'),
        ),
    ]
