# Generated by Django 3.2 on 2023-09-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20230914_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyplayedalbums',
            name='userdata',
        ),
        migrations.RemoveField(
            model_name='recentlyplayedplaylists',
            name='userdata',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='recently_played_albums',
        ),
        migrations.AddField(
            model_name='userdata',
            name='recently_played_albums',
            field=models.ManyToManyField(blank=True, related_name='recently_played_albums', to='userdata.RecentlyPlayedAlbums'),
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='recently_played_playlists',
        ),
        migrations.AddField(
            model_name='userdata',
            name='recently_played_playlists',
            field=models.ManyToManyField(blank=True, related_name='recently_played_playlists', to='userdata.RecentlyPlayedPlaylists'),
        ),
    ]
