# Generated by Django 3.2 on 2023-09-14 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlists', '0003_remove_playlist_likes'),
        ('songs', '0010_auto_20230914_0934'),
        ('userdata', '0004_auto_20230914_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlyplayedalbum',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recentlyplayedplaylist',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='recentlyplayedalbum',
            unique_together={('user', 'album')},
        ),
        migrations.AlterUniqueTogether(
            name='recentlyplayedplaylist',
            unique_together={('user', 'playlist')},
        ),
    ]
