# Generated by Django 3.2 on 2023-09-19 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20230914_0934'),
        ('playlists', '0003_remove_playlist_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdata', '0005_auto_20230914_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylistLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'playlist')},
            },
        ),
        migrations.CreateModel(
            name='UserArtistLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='UserAlbumLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.AddField(
            model_name='userdata',
            name='album_library',
            field=models.ManyToManyField(blank=True, related_name='album_library', to='userdata.UserAlbumLibrary'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='artist_library',
            field=models.ManyToManyField(blank=True, related_name='artist_library', to='userdata.UserArtistLibrary'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='playlist_library',
            field=models.ManyToManyField(blank=True, related_name='playlist_library', to='userdata.UserPlaylistLibrary'),
        ),
    ]
