# Generated by Django 3.2 on 2023-09-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20230919_0633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userartistlibrary',
            unique_together=set(),
        ),
    ]
