# Generated by Django 3.2 on 2023-09-25 16:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userdata', '0007_alter_userartistlibrary_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userartistlibrary',
            unique_together={('user', 'artist')},
        ),
    ]
